/**
 * Deutsche Spieltexte (S5.3, B-172): Quelle der Schlüssel. `texts.en.ts` hat denselben Typ, der Compiler erzwingt alle Schlüssel.
 * Platzhalter stehen als `{name}`. Deutsch ist Standard und Rückfall.
 */
export const de = {
  // Netz (Client-Verbindung)
  'net.connecting': 'Verbinde …',
  'net.reconnecting': 'Verbindung weg, verbinde neu …',
  'net.lost': 'Server nicht erreichbar',
  'net.replaced': 'An anderer Stelle geöffnet',
  'net.version': 'Veraltete Version, Seite neu laden',
  'net.unknownBiome': 'Unbekanntes Biom, Seite neu laden',

  // Laden
  'load.progress': 'Lade Grafiken … {pct} %',
  'load.failed': 'Laden fehlgeschlagen:\n{files}\n\nSeite neu laden (F5) oder Server prüfen.',
  'stage.loading': 'Stufe wird geladen',
  'stage.loadingN': 'Stufe {depth} wird geladen',

  // Lobby
  'lobby.title': 'Family Three Crowns',
  'lobby.hint': 'Pfeile/Stick wählen · A / Enter / Tippen bestätigen',
  'lobby.play': 'Spielen  ({save})',
  'lobby.retry': 'Erneut versuchen',
  'lobby.reload': 'Seite neu laden',
  'lobby.room': '{code}  {name}  ·  Stufe {depth}  ·  {taken}/4 Plätze  ·  {state}',
  'lobby.save': 'Spielstand {name}  ·  Tag {day}  ·  Stufe {depths}',
  'lobby.running': 'läuft',
  'lobby.paused': 'pausiert',

  // HUD: Hinweise
  'hud.hint.touch': 'Links/rechts berühren = laufen · Münz-Taste halten = Münzen geben',
  'hud.hint.pad': 'A halten = Münzen geben · RT = sprinten · RS = Vollbild',
  'hud.hint.keyboard': 'Leertaste halten = Münzen geben · Shift = sprinten · F = Vollbild',
  'hud.join.touch': 'Münz-Taste drücken zum Beitreten',
  'hud.join.pad': 'A drücken zum Beitreten',
  'hud.join.keyboard': 'Leertaste drücken zum Beitreten',
  'hud.joinCenter': 'Drücke  A  (Controller), Leertaste oder die Münz-Taste zum Beitreten',
  'hud.room': 'Raum {code} · {name} · {n} Spieler',

  // HUD: Werte
  'hud.travelUp': 'Aufstieg in Tiefe {depth}',
  'hud.travelDown': 'Abstieg in Tiefe {depth}',
  'hud.skillPoints': 'Skill-Punkte {n}',
  'hud.wave': 'Welle {wave}: {n} Gegner',
  'hud.down': 'gefallen · zurück in {s} s',
  'hud.downShort': '{s} s',
  'hud.hp': 'HP {hp}',
  'hud.playerShort': 'P{p} · {gold}/{max} · {status} · {stage}',
  'hud.playerFull': 'P{p}  ·  Gold {gold}/{max}  ·  {status}  ·  {stage}',
  'hud.clockDay': 'Tag {day}  ·  Dämmerung in {left}',
  'hud.clockDusk': 'Dämmerung  ·  Nacht in {left}',
  'hud.clockNight': 'Nacht {day}  ·  Morgen in {left}',
  'hud.aggression': '  ·  Aggression {pct}%',

  // Meldungen (Ereignisse)
  'ev.dusk': 'Nacht naht!',
  'ev.night': 'Nacht {day}',
  'ev.dawn': 'Tag {day}  –  die Sonne geht auf',
  'ev.wave': 'Portal öffnet sich!\n{n} Gegner kommen',
  'ev.chest': 'P{p} findet {gold} Gold',
  'ev.skillPoint': 'Skill-Punkt gefunden!',
  'ev.armed': 'Neuer Bogenschütze',
  'ev.built': '{name} fertig',
  'ev.destroyed': '{name} zerstört!',
  'ev.goldStolen': 'P{p}: {amount} Gold geklaut!',
  'ev.playerDown': 'P{p} ist gefallen',
  'ev.castleFallen': 'Die Burg ist gefallen!\nGebäude, Truppen und die Hälfte der Vorräte sind verloren',

  // Welt
  'exit.deeper': 'Tiefe {depth}\nalle hierher',
  'exit.blocked': 'verschüttet',
  'site.waitingWorker': '{name}: wartet auf Bauer',
  'site.missing': '{n} {res} fehlt',
  'site.ready': 'bereit',
  'site.bow': 'Bogen',

  // Namen (Schlüssel = ID aus den Daten, Daten bleiben unverändert)
  'site.wall': 'Mauer',
  'site.tower': 'Turm',
  'site.gate': 'Tor',
  'site.workshop': 'Werkstatt',
  'site.storage': 'Lager',
  'site.stairsUp': 'Treppe hoch',
  'site.stairsDown': 'Treppe runter',
  'site.farm': 'Farm',
  'site.barracks': 'Kaserne',
  'site.tavern': 'Taverne',
  'site.healer': 'Heilplatz',
  'site.smithy': 'Schmiede',
  'site.armory': 'Rüstkammer',
  'res.wood': 'Holz',
  'res.stone': 'Stein',
  'res.copper': 'Kupfer',
  'res.iron': 'Eisen',
  'res.crystal': 'Kristall',

  // Wirtschaft (W6.1): Wartegrund, Lager, Hub; kurze Form für 3 bis 4 Spieler
  'wait.worker': 'wartet auf Bauer',
  'wait.workerShort': 'kein Bauer',
  'wait.material': 'wartet auf Material ({res})',
  'wait.materialAny': 'wartet auf Material',
  'wait.materialShort': 'Material fehlt',
  'wait.danger': 'wartet: Gefahr',
  'wait.dangerShort': 'Gefahr',
  'stock.amount': '{res} {n}',
  'stock.ofMax': '{res} {n}/{max}',
  'stock.full': '{res} {n}/{max} voll',
  'stock.fullShort': '{res} voll',
  'cost.item': '{n} {res}',
  'cost.gold': '{paid}/{gold} Gold',
  'hub.level': 'Hub-Stufe {n}',
  'hub.levelShort': 'Hub {n}',
  'hub.upgrade': 'Hub-Stufe {n} → {next}: {cost}',
  'hub.upgradeShort': 'Hub {n}→{next}: {cost}',
  // Bürger (W6.1): Limit, Berufe, Händler
  'limit.text': 'Kämpfer {n} von {max}',
  'limit.full': 'Kämpfer {n} von {max}: Limit erreicht',
  'limit.short': 'Limit {n}/{max}',
  'limit.fullShort': 'Limit {n}/{max} voll',
  'prof.miner': 'Bergmann',
  'prof.builder': 'Baumeister',
  'prof.craftsman': 'Handwerker',
  'prof.unknown': 'Beruf',
  'prof.minerShort': 'Bergm.',
  'prof.builderShort': 'Baum.',
  'prof.craftsmanShort': 'Handw.',
  'prof.unknownShort': 'Beruf',
  'prof.count': '{name} {n}',
  'merchant.text': 'Händler: {res} · bis Tag {day}',
  'merchant.paid': 'Händler: {res} · bis Tag {day} · Kauf {paid} Gold',
  'merchant.short': 'Händler {res}',
  'biome.forest': 'Oberwelt (Wald)',
  'biome.cave': 'Tiefe 1 (Höhle)',
  'biome.mine': 'Tiefe 2 (Mine)',

  // Optionen und Pause
  'opt.title': 'Optionen',
  'opt.music': 'Musik',
  'opt.sfx': 'Effekte',
  'opt.screenshake': 'Wackeln',
  'opt.flash': 'Blitze',
  'opt.colorblind': 'Farbschwäche-Symbole',
  'opt.language': 'Sprache',
  'opt.guide': 'Hinweise (erste Nacht)',
  'opt.resume': 'Weiter',
  'opt.leave': 'Spiel verlassen',
  'opt.on': 'an',
  'opt.off': 'aus',
  'opt.hint': 'Hoch/Runter wählen · Links/Rechts ändern · A / Enter umlegen · Menu / Esc schließen',
  'opt.openButton': 'Optionen',
  // Skill-Menü und Skill-Leiste (S3.2)
  'skill.title': 'Skills  ·  {n} Punkte frei',
  'skill.learned': 'gelernt',
  'skill.learnable': 'lernen',
  'skill.locked': '–',
  'skill.passive': 'passiv',
  'skill.respec': 'Alle Skills zurücksetzen (Respec)',
  'skill.free': '–',
  'skill.ready': 'bereit',
  'skill.hint.pad': '◀ ▶ wählen · A bestätigen · {menu} schließen',
  'skill.hint.keyboard': 'A / D wählen · Leertaste bestätigen · {menu} schließen',
  'skill.hint.touch': 'Links/rechts wählen · Münz-Taste bestätigt · {menu} schließt',
  // Aktionen-Overlay (S3.3)
  'hint.hold': '{key} halten: {what}',
  'hint.press': '{key}: {what}',
  'hint.space': 'Leertaste',
  'hint.build': '{name} bauen',
  'hint.pay': '{name} kaufen',
  'hint.revive': 'Wiederbeleben',
  'hint.attack': 'Schlag',
  'cast.noTarget': 'kein Ziel',
  'hint.learn': 'Skill lernen',
  'hint.respec': 'Skills zurücksetzen',
  // Geführte erste Nacht (S6.3): Hinweise über den Objekten, {key} = Glyph
  'guide.coin': 'Hinlaufen: Münze aufheben',
  'guide.pay': '{key} halten: Bauplatz bezahlen',
  'guide.dusk': 'Die Nacht naht! Zurück zur Burg',
  'guide.recruit': '{key} halten: Münze geben, er wird Bauer',
  'lang.de': 'Deutsch',
  'lang.en': 'English',
  // Shell (Home-Button) und Touch-Overlay (B-215)
  'shell.home': 'Start',
  'shell.homeTitle': 'Zurück zur Startseite (View + Menu, Pos1)',
  'touch.fullscreen': 'Vollbild',
  'touch.sprint': 'Sprinten',
  'touch.attack': 'Schlag',
  'touch.confirm': 'Münzen geben / beitreten',
  'touch.skill1': 'Skill 1',
  'touch.skill2': 'Skill 2',
  'touch.skill3': 'Skill 3',
  'touch.skill4': 'Skill 4',
  'touch.skillMenu': 'Skill-Menü',
  // Landingpage (B-369)
  'landing.tagline': 'Couch-Koop für die ganze Familie',
  'landing.section.play': 'Spielen',
  'landing.section.about': 'Über das Spiel',
  'landing.continue': 'Weiterspielen',
  'landing.continue.desc': 'Lobby öffnen · letzten Spielstand wählen · speichert automatisch bei Tagesanbruch',
  'landing.new': 'Neues Spiel',
  'landing.new.desc': 'Lobby öffnen · Oberwelt · frischer Spielstand mit eigenem Namen · bis zu 2 Spieler · alte Spielstände bleiben',
  'landing.online': 'Online spielen',
  'landing.online.desc': 'Lobby öffnen · Raum beitreten oder anlegen · mit Handy, Tablet oder PC, ein Monarch pro Gerät',
  'landing.licenses': 'Lizenzen & Danksagung',
  'landing.licenses.desc': 'Unsere Lizenz (nicht-kommerziell) · Grafiken, Software und ein großes Danke an alle Urheber',
  'landing.dev': 'Entwicklung',
  'landing.dev.desc': 'Werkzeuge für Entwicklung, Performance und Balancing',
  'landing.frame': 'Seite',
  'landing.padNone': 'Controller: Taste drücken',
  'landing.padCount': '{n} Controller verbunden',
  'landing.fullscreen': 'Vollbild',
  'landing.fullscreenExit': 'Vollbild beenden',
  'landing.fullscreenDenied': 'Der Browser erlaubt hier kein Vollbild. Auf der Xbox alternativ das Vollbild aus dem Edge-Menü nutzen.',
  'landing.fullscreenBlocked': 'Vollbild per {via} blockiert. Bitte mit dem Cursor auf „Vollbild“ klicken.',
  'landing.viaKey': 'Taste F',
  'landing.viaPad': 'Controller (Y)',
  'landing.hintSelect': '/ Stick auswählen',
  'landing.hintOpen': 'öffnen',
  'landing.hintBack': 'auf jeder Seite: zurück hierher',
  'landing.noServer': 'Braucht den Heimnetz-Server',
  'landing.noServerText':
    'Braucht den Heimnetz-Server. Das Spiel läuft nur auf dem Go-Server (task serve), nicht auf einer statischen Seite wie GitHub Pages. Mit dem Home-Button geht es zurück.',
};

export type TextKey = keyof typeof de;
