import type { TextKey } from './texts.de';

/** Englische Spieltexte (S5.3): kurz gehalten, Länge ähnlich der deutschen (Mindest-Schriftgröße, Q03). */
export const en: Record<TextKey, string> = {
  'net.connecting': 'Connecting …',
  'net.reconnecting': 'Connection lost, reconnecting …',
  'net.lost': 'Server not reachable',
  'net.replaced': 'Opened somewhere else',
  'net.version': 'Outdated version, reload the page',
  'net.unknownBiome': 'Unknown biome, reload the page',

  'load.progress': 'Loading graphics … {pct} %',
  'load.failed': 'Loading failed:\n{files}\n\nReload the page (F5) or check the server.',
  'stage.loading': 'Loading level',
  'stage.loadingN': 'Loading level {depth}',

  'lobby.title': 'Family Three Crowns',
  'lobby.hint': 'Arrows/stick select · A / Enter / tap confirm',
  'lobby.play': 'Play  ({save})',
  'lobby.retry': 'Try again',
  'lobby.reload': 'Reload page',
  'lobby.room': '{code}  {name}  ·  Level {depth}  ·  {taken}/4 seats  ·  {state}',
  'lobby.running': 'running',
  'lobby.paused': 'paused',

  'hud.hint.touch': 'Touch left/right = walk · hold coin button = give coins',
  'hud.hint.pad': 'Hold A = give coins · RT = sprint · RS = fullscreen',
  'hud.hint.keyboard': 'Hold Space = give coins · Shift = sprint · F = fullscreen',
  'hud.join.touch': 'Press the coin button to join',
  'hud.join.pad': 'Press A to join',
  'hud.join.keyboard': 'Press Space to join',
  'hud.joinCenter': 'Press  A  (controller), Space or the coin button to join',
  'hud.room': 'Room {code} · {name} · {n} players',

  'hud.travelUp': 'Going up to depth {depth}',
  'hud.travelDown': 'Going down to depth {depth}',
  'hud.skillPoints': 'Skill points {n}',
  'hud.wave': 'Wave {wave}: {n} enemies',
  'hud.down': 'down · back in {s} s',
  'hud.downShort': '{s} s',
  'hud.hp': 'HP {hp}',
  'hud.playerShort': 'P{p} · {gold}/{max} · {status} · {stage}',
  'hud.playerFull': 'P{p}  ·  Gold {gold}/{max}  ·  {status}  ·  {stage}',
  'hud.clockDay': 'Day {day}  ·  Dusk in {left}',
  'hud.clockDusk': 'Dusk  ·  Night in {left}',
  'hud.clockNight': 'Night {day}  ·  Morning in {left}',
  'hud.aggression': '  ·  Aggression {pct}%',

  'ev.dusk': 'Night is coming!',
  'ev.night': 'Night {day}',
  'ev.dawn': 'Day {day}  –  the sun rises',
  'ev.wave': 'Portal opens!\n{n} enemies are coming',
  'ev.chest': 'P{p} finds {gold} gold',
  'ev.skillPoint': 'Skill point found!',
  'ev.armed': 'New archer',
  'ev.built': '{name} built',
  'ev.destroyed': '{name} destroyed!',
  'ev.goldStolen': 'P{p}: {amount} gold stolen!',
  'ev.playerDown': 'P{p} is down',
  'ev.castleFallen': 'The castle has fallen!\nBuildings, troops and half the supplies are lost',

  'exit.deeper': 'Depth {depth}\neveryone here',
  'exit.blocked': 'caved in',
  'site.waitingWorker': '{name}: waiting for a peasant',
  'site.missing': '{n} {res} missing',
  'site.ready': 'ready',
  'site.bow': 'Bow',

  'site.wall': 'Wall',
  'site.tower': 'Tower',
  'site.gate': 'Gate',
  'site.workshop': 'Workshop',
  'site.storage': 'Storage',
  'site.stairsUp': 'Stairs up',
  'site.stairsDown': 'Stairs down',
  'site.farm': 'Farm',
  'site.barracks': 'Barracks',
  'site.tavern': 'Tavern',
  'site.healer': 'Healer',
  'site.smithy': 'Smithy',
  'site.armory': 'Armory',
  'res.wood': 'Wood',
  'res.stone': 'Stone',
  'res.copper': 'Copper',
  'biome.forest': 'Overworld (forest)',
  'biome.cave': 'Depth 1 (cave)',
  'biome.mine': 'Depth 2 (mine)',

  'opt.title': 'Options',
  'opt.music': 'Music',
  'opt.sfx': 'Effects',
  'opt.screenshake': 'Shake',
  'opt.flash': 'Flashes',
  'opt.colorblind': 'Colorblind symbols',
  'opt.language': 'Language',
  'opt.guide': 'Hints (first night)',
  'opt.resume': 'Resume',
  'opt.leave': 'Leave game',
  'opt.on': 'on',
  'opt.off': 'off',
  'opt.hint': 'Up/Down select · Left/Right change · A / Enter toggle · Menu / Esc close',
  'opt.openButton': 'Options',
  // Skill menu and skill bar (S3.2)
  'skill.title': 'Skills  ·  {n} points free',
  'skill.learned': 'learned',
  'skill.learnable': 'learn',
  'skill.locked': '–',
  'skill.passive': 'passive',
  'skill.respec': 'Reset all skills (respec)',
  'skill.free': '–',
  'skill.ready': 'ready',
  'skill.hint.pad': '◀ ▶ select · A confirm · {menu} close',
  'skill.hint.keyboard': 'A / D select · Space confirm · {menu} close',
  'skill.hint.touch': 'Left/right select · coin button confirms · {menu} closes',
  // Action overlay (S3.3)
  'hint.hold': 'Hold {key}: {what}',
  'hint.press': '{key}: {what}',
  'hint.space': 'Space',
  'hint.build': 'build {name}',
  'hint.pay': 'buy {name}',
  'hint.revive': 'revive',
  'hint.attack': 'strike',
  'hint.learn': 'learn skill',
  'hint.respec': 'reset skills',
  // Guided first night (S6.3): hints above objects, {key} = glyph
  'guide.coin': 'Walk over it: pick up the coin',
  'guide.pay': 'Hold {key}: pay for the build site',
  'guide.dusk': 'Night is coming! Back to the castle',
  'guide.recruit': 'Hold {key}: give a coin, he becomes a peasant',
  'lang.de': 'Deutsch',
  'lang.en': 'English',
};
