/**
 * Deutsche Texte der Werkzeug-Seiten (PL2, B-322): Quelle der Schlüssel, nach Seite gruppiert. Platzhalter stehen als `{name}`.
 * Deutsch ist Standard und Rückfall.
 */
export const de = {
  // Level-Betrachter (leveltest.html)
  'level.pageTitle': 'K3C Level-Betrachter',
  'level.title': 'Level-Betrachter',
  'level.sub': 'Zeigt das Level, das ein Raum mit diesem Seed und Biom bekäme, ohne zu spielen. Voraussetzung: der Go-Server läuft',
  'level.seed': 'Seed',
  'level.biome': 'Biom',
  'level.random': 'Zufälliger Seed',
  'level.load': 'Laden',
  'level.start': 'Im Spiel starten',
  'level.keys': 'Scrollen: linker Stick oder Pfeiltasten · Zoom: LB/RB oder + / − · Auswahl: Steuerkreuz hoch/runter, A drücken',
  'level.replaces': 'Der Start öffnet den Spielstand mit dem Seed als Namen: gibt es ihn schon, wird er weitergespielt, sonst entsteht ein neues Spiel mit diesem Level.',
  'level.cannotStart': 'Im Spiel starten nicht möglich: {reason}.',
  'level.chunkTitle': 'Abschnitt {index}: {kind} ({from}–{to} Units)',
  'level.objectTitle': '{kind} bei {x} Units',
  'level.hubTitle': 'Hub-Mitte bei {x} Units',
  'level.loading': 'Lade …',
  'level.summary': 'Seed „{seed}“ · {biome} · {width} Units · {chunks} Abschnitte · {objects} Objekte',
  'level.incomplete': 'Antwort unvollständig',
  'level.forestOnly': 'Start nur für den Wald (Tiefe 0)',
  'level.badSeed': 'Seed muss aus Kleinbuchstaben, Ziffern und - bestehen (höchstens 32 Zeichen)',
  'level.unreachable': 'Server nicht erreichbar. Starte ihn mit `task start`.',
  'level.invalid': 'Die Antwort des Servers ist kein gültiges Level.',
  'level.httpError': 'Fehler {status}',

  // Hörprobe (soundtest.html)
  'sound.pageTitle': 'K3C Hörprobe',
  'sound.title': 'Hörprobe',
  'sound.sub': 'Kandidaten für Musik und Effekte anhören, nach Zustand und Ereignis geordnet, mit Quelle und Lizenz.',
  'sound.pressKey': 'Taste drücken zum Entsperren',
  'sound.stop': 'Stopp',
  'sound.fade': 'Überblenden',
  'sound.volDown': 'Leiser −',
  'sound.volDownAria': 'Leiser',
  'sound.volUp': 'Lauter +',
  'sound.volUpAria': 'Lauter',
  'sound.keys':
    'Controller: Steuerkreuz/Stick wählt, A spielt, X stoppt, Y überblendet das gewählte Stück ein, LB/RB Lautstärke. ' +
    'Tastatur: Pfeile hoch/runter wählen, Enter spielt, S stoppt, X überblendet, Pfeile links/rechts oder −/+ Lautstärke. Touch: Eintrag antippen, Knöpfe oben.',
  'sound.kindState': 'Zustand',
  'sound.kindEvent': 'Ereignis',
  'sound.failed': '{name} (lädt nicht)',
  'sound.meta': 'Quelle: {source} · Lizenz: {license}',
  'sound.playing': 'Spielt: {name}',
  'sound.silence': 'Stille',
  'sound.status': '{state} · Lautstärke {volume} %',
  'sound.noFormat': 'kein abspielbares Format',
  'sound.unlocked': 'Audio entsperrt',
  'sound.locked': 'Audio gesperrt: Taste drücken, Bildschirm antippen oder A am Controller',

  // Monitoring-Seite (monitor.html)
  'monitor.pageTitle': 'K3C Monitor',
  'monitor.connecting': 'Verbinde …',
  'monitor.saveToken': 'Token speichern',
  'monitor.tab.overview': 'Übersicht',
  'monitor.tab.history': 'Verlauf',
  'monitor.tab.events': 'Ereignisse',
  'monitor.h.tick': 'Tick-Dauer (max je s)',
  'monitor.h.rtt': 'RTT je Gerät',
  'monitor.h.server': 'Server: Heap und CPU',
  'monitor.legend': 'Rote Punkte: Ausreißer. Striche unten: Diagnose-Ereignisse. Gestrichelt: Neustart. ▼: gewähltes Ereignis.',
  'monitor.keys': 'Controller: Steuerkreuz/Stick wählt, A bestätigt. Touch und Maus: antippen.',
  'monitor.kind.crash': '💥 Absturz',
  'monitor.kind.slow': '🐢 langsamer Tick',
  'monitor.kind.drop': '👋 Trennung',
  'monitor.kind.client': '📨 Client-Fehler',
  'monitor.rooms': 'Räume (letzte 5 min)',
  'monitor.noRoom': 'Kein Raum aktiv.',
  'monitor.noPong': 'kein Pong',
  'monitor.roomLine': 'Tick p99 {tick} · RTT {rtt} · Fehler {errors}',
  'monitor.serverLine': 'Heap {heap} MB · CPU {cpu} · Goroutinen {goroutines}',
  'monitor.restart': 'Neustart',
  'monitor.heapMB': 'Heap MB',
  'monitor.all': 'alle',
  'monitor.roomFilter': 'Raum: {room}',
  'monitor.kindFilter': 'Art: {kind}',
  'monitor.window1h': 'Fenster 1 h',
  'monitor.window5m': 'Fenster 5 min',
  'monitor.overBudget': 'Budget überschritten',
  'monitor.ticks': '{n} Ticks',
  'monitor.noEvents': 'Keine Ereignisse in der letzten Stunde.',
  'monitor.eventRoom': ' · Raum {room}',
  'monitor.tokenAsk': '🔒 Token eingeben (K3C_STATUS_TOKEN des Servers).',
  'monitor.tokenBad': '🔒 Token fehlt oder ist falsch, bitte neu eingeben.',
  'monitor.ok': '✅ Stand {now} · Server seit {since}',
  'monitor.off': '🚫 Diagnose aus, K3C_STATUS_TOKEN am Server setzen.',
  'monitor.offline': '❌ Server nicht erreichbar, nächster Versuch in {wait} s.',

  // Dungeon-Master-Seite (dm.html)
  'dm.pageTitle': 'K3C Dungeon Master',
  'dm.back': '← Raumliste',
  'dm.actions': 'Aktionen',
  'dm.monarchLabel': 'Monarch',
  'dm.rooms': 'Räume',
  'dm.noRoom': 'Kein Raum offen.',
  'dm.idle': ' · ruht',
  'dm.room': 'Raum {code}',
  'dm.row.tick': 'Takt',
  'dm.row.time': 'Zeit',
  'dm.row.wave': 'Welle',
  'dm.row.castle': 'Burg',
  'dm.row.gold': 'Gold',
  'dm.row.troops': 'Truppen',
  'dm.row.devices': 'Verbindungen',
  'dm.row.stages': 'Stufen',
  'dm.timeValue': 'Tag {day} · {phase} · {speed}',
  'dm.waveValue': '{wave} · Gegner {enemies}',
  'dm.monarch': 'Monarch {n}',
  'dm.unreachable': 'Server nicht erreichbar',
  'dm.devOn': 'Dev-Mode an · Aktionen aktiv',
  'dm.devOff': 'Dev-Mode aus · nur Diagnose',
  'dm.gold': '🪙 +50 Gold',
  'dm.material': '📦 +20 {resource}',
  'dm.timescale': '⏩ Zeit {factor}×',
  'dm.pause': '⏸ Pause',
  'dm.resume': '▶ Weiter',
  'dm.wave': '🌙 Welle',
  'dm.day': '☀ Tag',
  'dm.dusk': '🌆 Dämmerung',
  'dm.night': '🌑 Nacht',

  // Grafik-Seite (grafiken.html) und Credits (lizenzen.html)
  'grafik.pageTitle': 'K3C Alle Grafiken',
  'grafik.title': 'Alle Grafiken',
  'grafik.sub1':
    'Die für B-010 gewählten Pixel-Art-Packs für Gebäude, Ressourcen und Hintergründe, mit Urheber, Lizenz und Quelle. Nur die Umgebungs-Bilder sind im Spiel-Ordner',
  'grafik.sub2':
    'Scrollen mit Stick oder Steuerkreuz. Mit den Kästchen „Auswahl“ (je Pack und je Bild) stellst du unten einen Satz mit IDs zusammen, den du im Chat nennen kannst.',
  'grafik.zoom': 'Vergrößerung',
  'grafik.missing': 'Bild fehlt',
  'grafik.source': 'Quelle',
  'grafik.noIndex': 'Die Bildliste grafik/index.json lässt sich nicht laden.',
  'grafik.group.ebenen': 'Ebenen und Tilesets',
  'grafik.group.umgebung': 'Umgebung',
  'grafik.group.props': 'Props',
  'grafik.group.props-einzeln': 'Props einzeln',
  'grafik.group.tileset-einzeln': 'Tileset einzeln',
  'grafik.group.ressourcen': 'Ressourcen',
  'grafik.group.portale': 'Portale',
  'grafik.group.muenzen': 'Münzen',
  'grafik.group.icons': 'Symbole',
  'grafik.group.vorschau': 'Vorschau',
  'credits.work': 'Werk',
  'credits.author': 'Urheber:innen',
  'credits.license': 'Lizenz',
  'credits.source': 'Quelle',
  'credits.attribution': 'Namensnennung',
} as const satisfies Record<string, string>;

export type ToolTextKey = keyof typeof de;
