import type { ToolTextKey } from './texts.de';

/** Englische Texte der Werkzeug-Seiten (PL2, B-322); ein fehlender Schlüssel fällt auf Deutsch zurück. */
export const en: Partial<Record<ToolTextKey, string>> = {
  // Level viewer (leveltest.html)
  'level.pageTitle': 'K3C Level Viewer',
  'level.title': 'Level Viewer',
  'level.sub': 'Shows the level a room would get with this seed and biome, without playing. Requires the Go server to be running',
  'level.seed': 'Seed',
  'level.biome': 'Biome',
  'level.random': 'Random seed',
  'level.load': 'Load',
  'level.start': 'Start in game',
  'level.keys': 'Scroll: left stick or arrow keys · Zoom: LB/RB or + / − · Select: D-pad up/down, press A',
  'level.replaces': 'Starting opens the save named after the seed: if it exists it continues, otherwise a new game with this level begins.',
  'level.cannotStart': 'Cannot start in game: {reason}.',
  'level.chunkTitle': 'Chunk {index}: {kind} ({from}–{to} units)',
  'level.objectTitle': '{kind} at {x} units',
  'level.hubTitle': 'Hub center at {x} units',
  'level.loading': 'Loading …',
  'level.summary': 'Seed “{seed}” · {biome} · {width} units · {chunks} chunks · {objects} objects',
  'level.incomplete': 'Incomplete response',
  'level.forestOnly': 'Start only works for the forest (depth 0)',
  'level.badSeed': 'Seed must consist of lowercase letters, digits and - (at most 32 characters)',
  'level.unreachable': 'Server not reachable. Start it with `task start`.',
  'level.invalid': 'The server response is not a valid level.',
  'level.httpError': 'Error {status}',

  // Sound test (soundtest.html)
  'sound.pageTitle': 'K3C Sound Test',
  'sound.title': 'Sound Test',
  'sound.sub': 'Listen to music and effect candidates, ordered by state and event, with source and license.',
  'sound.pressKey': 'Press a key to unlock',
  'sound.stop': 'Stop',
  'sound.fade': 'Crossfade',
  'sound.volDown': 'Quieter −',
  'sound.volDownAria': 'Quieter',
  'sound.volUp': 'Louder +',
  'sound.volUpAria': 'Louder',
  'sound.keys':
    'Controller: D-pad/stick selects, A plays, X stops, Y crossfades to the selected track, LB/RB volume. ' +
    'Keyboard: arrows up/down select, Enter plays, S stops, X crossfades, arrows left/right or −/+ volume. Touch: tap an entry, buttons on top.',
  'sound.kindState': 'State',
  'sound.kindEvent': 'Event',
  'sound.failed': '{name} (does not load)',
  'sound.meta': 'Source: {source} · License: {license}',
  'sound.playing': 'Playing: {name}',
  'sound.silence': 'Silence',
  'sound.status': '{state} · Volume {volume} %',
  'sound.noFormat': 'no playable format',
  'sound.unlocked': 'Audio unlocked',
  'sound.locked': 'Audio locked: press a key, tap the screen or press A on the controller',

  // Monitoring page (monitor.html)
  'monitor.pageTitle': 'K3C Monitor',
  'monitor.connecting': 'Connecting …',
  'monitor.saveToken': 'Save token',
  'monitor.tab.overview': 'Overview',
  'monitor.tab.history': 'History',
  'monitor.tab.events': 'Events',
  'monitor.h.tick': 'Tick duration (max per s)',
  'monitor.h.rtt': 'RTT per device',
  'monitor.h.server': 'Server: heap and CPU',
  'monitor.legend': 'Red dots: outliers. Marks below: diagnostic events. Dashed: restart. ▼: selected event.',
  'monitor.keys': 'Controller: D-pad/stick selects, A confirms. Touch and mouse: tap.',
  'monitor.kind.crash': '💥 Crash',
  'monitor.kind.slow': '🐢 Slow tick',
  'monitor.kind.drop': '👋 Disconnect',
  'monitor.kind.client': '📨 Client error',
  'monitor.rooms': 'Rooms (last 5 min)',
  'monitor.noRoom': 'No active room.',
  'monitor.noPong': 'no pong',
  'monitor.roomLine': 'Tick p99 {tick} · RTT {rtt} · Errors {errors}',
  'monitor.serverLine': 'Heap {heap} MB · CPU {cpu} · Goroutines {goroutines}',
  'monitor.restart': 'Restart',
  'monitor.heapMB': 'Heap MB',
  'monitor.all': 'all',
  'monitor.roomFilter': 'Room: {room}',
  'monitor.kindFilter': 'Kind: {kind}',
  'monitor.window1h': 'Window 1 h',
  'monitor.window5m': 'Window 5 min',
  'monitor.overBudget': 'Budget exceeded',
  'monitor.ticks': '{n} ticks',
  'monitor.noEvents': 'No events in the last hour.',
  'monitor.eventRoom': ' · Room {room}',
  'monitor.tokenAsk': '🔒 Enter token (K3C_STATUS_TOKEN of the server).',
  'monitor.tokenBad': '🔒 Token missing or wrong, please enter it again.',
  'monitor.ok': '✅ As of {now} · Server since {since}',
  'monitor.off': '🚫 Diagnostics off, set K3C_STATUS_TOKEN on the server.',
  'monitor.offline': '❌ Server not reachable, next attempt in {wait} s.',

  // Dungeon master page (dm.html)
  'dm.pageTitle': 'K3C Dungeon Master',
  'dm.back': '← Room list',
  'dm.actions': 'Actions',
  'dm.monarchLabel': 'Monarch',
  'dm.rooms': 'Rooms',
  'dm.noRoom': 'No open room.',
  'dm.idle': ' · idle',
  'dm.room': 'Room {code}',
  'dm.row.tick': 'Tick',
  'dm.row.time': 'Time',
  'dm.row.wave': 'Wave',
  'dm.row.castle': 'Castle',
  'dm.row.gold': 'Gold',
  'dm.row.troops': 'Troops',
  'dm.row.devices': 'Connections',
  'dm.row.stages': 'Stages',
  'dm.timeValue': 'Day {day} · {phase} · {speed}',
  'dm.waveValue': '{wave} · Enemies {enemies}',
  'dm.monarch': 'Monarch {n}',
  'dm.unreachable': 'Server not reachable',
  'dm.devOn': 'Dev mode on · actions active',
  'dm.devOff': 'Dev mode off · diagnostics only',
  'dm.gold': '🪙 +50 gold',
  'dm.material': '📦 +20 {resource}',
  'dm.timescale': '⏩ Speed {factor}×',
  'dm.pause': '⏸ Pause',
  'dm.resume': '▶ Resume',
  'dm.wave': '🌙 Wave',
  'dm.day': '☀ Day',
  'dm.dusk': '🌆 Dusk',
  'dm.night': '🌑 Night',

  // Graphics page (grafiken.html) and credits (lizenzen.html)
  'grafik.pageTitle': 'K3C All Graphics',
  'grafik.title': 'All Graphics',
  'grafik.sub1':
    'The pixel art packs chosen for B-010 for buildings, resources and backgrounds, with author, license and source. Only the environment images are in the game folder',
  'grafik.sub2':
    'Scroll with stick or D-pad. With the “Selection” boxes (per pack and per image) you build a set of IDs below that you can mention in the chat.',
  'grafik.zoom': 'Zoom',
  'grafik.missing': 'Image missing',
  'grafik.source': 'Source',
  'grafik.noIndex': 'The image list grafik/index.json cannot be loaded.',
  'grafik.group.ebenen': 'Layers and tilesets',
  'grafik.group.umgebung': 'Environment',
  'grafik.group.props': 'Props',
  'grafik.group.props-einzeln': 'Single props',
  'grafik.group.tileset-einzeln': 'Single tilesets',
  'grafik.group.ressourcen': 'Resources',
  'grafik.group.portale': 'Portals',
  'grafik.group.muenzen': 'Coins',
  'grafik.group.icons': 'Icons',
  'grafik.group.vorschau': 'Preview',
  'credits.work': 'Work',
  'credits.author': 'Author(s)',
  'credits.license': 'License',
  'credits.source': 'Source',
  'credits.attribution': 'attribution',

  // Developer page (dev.html) and its tiles; the tiles also appear on testing.html
  'dev.pageTitle': 'K3C Development',
  'dev.title': 'Development',
  'dev.sub': 'Tools for development, performance and balancing. Most of them need the Go server running.',
  'dev.section.dev': 'Development',
  'dev.section.perf': 'Performance',
  'dev.section.balance': 'Balancing',
  'dev.empty': 'No entries yet.',
  'tool.opening': 'Opening “{title}” …',
  'dev.opensWindow': '“{title}” opens in a new window.',
  'dev.blocked': 'New window blocked: please open {url} by hand.',
  'tile.testing.title': 'Testing',
  'tile.testing.desc': 'Start test scenarios · 1 to 4 players with mock players (Go server required)',
  'tile.level.title': 'Level Viewer',
  'tile.level.desc': 'Pick seed and biome, view the generated level · validation warnings (Go server required)',
  'tile.gamepad.title': 'Gamepad Test',
  'tile.gamepad.desc': 'Controller, B button, fullscreen, rumble, FPS · report to the PC',
  'tile.aufstellung.title': 'Our Lineup',
  'tile.aufstellung.desc': 'Every role in the game with its figure · monarchs, troops, enemies',
  'tile.figuren.title': 'All Figures',
  'tile.figuren.desc': 'All sprites from LuizMelo and Gothicvania, including unused ones',
  'tile.grafiken.title': 'All Graphics',
  'tile.grafiken.desc': 'Chosen CC0 packs for buildings, resources and backgrounds · with author, license and source',
  'tile.sound.title': 'Listening Test',
  'tile.sound.desc': 'Listen to candidates for music and effects · by state and event, with source and license',
  'tile.dm.title': 'Dungeon Master',
  'tile.dm.desc': 'Watch and control running rooms: time, pause, gold, material, wave, time of day · new window (server dev mode)',
  'tile.monitor.title': 'Monitor',
  'tile.monitor.desc': 'Server state: traffic light per room, history with percentiles, error timeline (Go server with K3C_STATUS_TOKEN)',

  // Test page (testing.html)
  'test.pageTitle': 'K3C Testing',
  'test.title': 'Testing',
  'test.sub':
    'Start test scenarios or view a level. You are player 1, the other players are mock players on the same device: they appear at once and stand still. Requires the Go server (<code>task serve:go</code>).',
  'test.h.players': 'Players',
  'test.h.level': 'Level',
  'test.starting': 'Starting “{title}” …',
  'test.sc.one.title': '1 player',
  'test.sc.n.title': '{n} players',
  'test.sc.one.desc': 'Fullscreen, no mock players',
  'test.sc.n.desc': 'You and {mocks} mock players (standing still) · {layout}',
  'test.layout.2': 'two strips',
  'test.layout.3': 'two on top, one wide below',
  'test.layout.4': '2×2 grid',

  // Reference pages (figuren.html, aufstellung.html) and the selection bar
  'fig.pageTitle': 'K3C All Figures',
  'fig.title': 'All Figures',
  'fig.sub':
    'All figures from LuizMelo (our side) and Gothicvania by ansimuz (enemy side), including those without a role yet. All CC0, sources in public/sprites/CREDITS.md. Each figure is fitted on its own. Scroll with stick or D-pad. With the “Selection” boxes you build a sentence of figure IDs below that you can mention in the chat.',
  'auf.pageTitle': 'K3C Our Lineup',
  'auf.title': 'Our Lineup',
  'auf.sub':
    'Every role in the game with image, tint and size from data/sprites.json. Monarchs, troops and enemies share one scale, just as their sizes relate in the game. Below are the figures that have no role yet. Scroll with stick or D-pad. With the “Selection” boxes you build a sentence of figure IDs below that you can mention in the chat.',
  'sprite.ours': 'Our side',
  'sprite.enemy': 'Enemy side',
  'sprite.mountsKing': 'Mounts (with king 1)',
  'sprite.monarchs': 'Monarchs',
  'sprite.troops': 'Troops',
  'sprite.enemies': 'Enemies',
  'sprite.mountsLater': 'Mounts (not in the game yet)',
  'sprite.reserve': 'Reserve (no role yet)',
  'sprite.noRole': 'no role yet',
  'sprite.tinted': 'tinted {tint}',
  'sprite.translucent': 'translucent',
  'sprite.player': 'Player {n}',
  'sprite.depth': '{name} · depth {depth}',
  'sprite.height': '{id} · {px} px tall in the game',
  'sel.pick': 'Selection',
  'sel.placeholder': 'Tick the “Selection” box, the text to copy appears here',
  'sel.copy': 'Copy',
  'sel.clear': 'Clear',
  'sel.text': 'Selection {label}: {ids}',
  'sel.figuren': 'figures',
  'sel.aufstellung': 'lineup',
  'sel.grafiken': 'graphics',

  // Gamepad test (gamepad-test.html) and its audio probe
  'pad.pageTitle': 'K3C Gamepad Test',
  'pad.sub':
    'Connect controllers and press a button on each. Green bar = button was detected at least once. Controller shortcuts: <kbd>Y</kbd> send report · <kbd>X</kbd> rumble · <kbd>View</kbd> FPS test · <kbd>Menu</kbd> try fullscreen. Audio test: first read the Audio section, then press <kbd>A</kbd> (gesture) and afterwards <kbd>Y</kbd> to send. Please press <kbd>B</kbd> once as well. Back to the start page: hold <kbd>View</kbd>+<kbd>Menu</kbd>.',
  'pad.h.actions': 'Actions',
  'pad.btn.fullscreen': 'Fullscreen',
  'pad.btn.perf': 'Start FPS test',
  'pad.btn.rumble': 'Test rumble',
  'pad.btn.report': 'Send report to server',
  'pad.h.env': 'Environment',
  'pad.h.audio': 'Audio',
  'pad.btn.audio': 'Unlock audio and play test tone',
  'pad.h.pads': 'Controllers',
  'pad.none': 'No controller detected yet. Press a button on the controller.',
  'pad.h.log': 'Events',
  'pad.env.secure': 'Secure Context',
  'pad.env.gamepadApi': 'Gamepad API',
  'pad.env.fullscreenApi': 'Fullscreen API',
  'pad.env.secureYes': 'yes (HTTPS/localhost)',
  'pad.env.secureNo': 'no (HTTP)',
  'pad.env.present': 'available',
  'pad.env.missing': 'missing',
  'pad.env.screen': 'Screen',
  'pad.env.screenValue': '{screen} · window {w}x{h} · DPR {dpr}',
  'pad.env.back': 'Back navigations',
  'pad.axis': 'Axis {i}',
  'pad.buttonN': 'Button {i}',
  'pad.sending': 'Sending …',
  'pad.sent': '✔ Report saved ({time})',
  'pad.sendFailed': '✘ Sending failed: {error}',
  'pad.on': 'on',
  'pad.off': 'off',
  'pad.noValues': 'no values',
  'pad.audioRunning': 'Probe running …',
  'pad.log.reportSent': 'Report sent',
  'pad.log.key': 'Key: {entry}',
  'pad.log.visibility': 'Visibility: {state}',
  'pad.log.connected': '🎮 connected: #{index} {id}',
  'pad.log.disconnected': '🎮 disconnected: #{index} {id}',
  'pad.log.fullscreen': 'Fullscreen: {state}',
  'pad.log.fsOk': 'Fullscreen via {via}: ok',
  'pad.log.fsFailed': 'Fullscreen via {via} failed: {error}',
  'pad.log.rumbleNone': 'Rumble: no controller',
  'pad.log.rumbleOk': 'Rumble #{index}: ok',
  'pad.log.rumbleError': 'Rumble #{index}: {error}',
  'pad.log.pressed': '#{index} {name} pressed',
  'pad.log.perfEnd': 'FPS test finished: {values}',
  'pad.log.back': '⚠ Back navigation triggered (B button?)',
  'pad.log.ready': 'Ready. Press a button on a controller.',
  'pad.log.noApi': 'Gamepad API not available!',
  'pad.perf.done': 'Done · {values} · View = back',
  'pad.perf.running': '{n} sprites · {fps} FPS · step {step}/{steps} · View = cancel',
  'audio.beforeGesture': 'State before gesture',
  'audio.afterGesture': 'State after gesture',
  'audio.noGestureYet': 'no gesture yet',
  'audio.gestures': 'Gestures',
  'audio.autoplay': 'Playback without gesture',
  'audio.played': 'played',
  'audio.blocked': 'blocked',
  'audio.error': 'error: {name}',
  'audio.format': 'Format {format}',
  'audio.yes': 'yes',
  'audio.no': 'no',
  'audio.latency': 'Latency',
  'audio.latencyValue': 'Base {base} · output {out}',
  'audio.unknown': 'unknown',
  'audio.none': 'no audio (no AudioContext)',
  'audio.via.controller': 'controller',
  'audio.via.taste': 'key',
  'audio.via.klick': 'click',

  // Licenses page (lizenzen.html); texts with HTML are set via data-t-html
  'lic.pageTitle': 'K3C Licenses & Credits',
  'lic.title': 'Licenses & Credits',
  'lic.sub':
    'Family Three Crowns (K3C) is a family project and stands on the shoulders of many generous people. This page lists the license our game runs under and whom we thank for graphics, libraries and tools. Scroll with stick or D-pad.',
  'lic.h.ours': 'Our license',
  'lic.boxCode':
    '<strong>Source code:</strong> <a href="https://polyformproject.org/licenses/noncommercial/1.0.0" target="_blank" rel="noopener">PolyForm Noncommercial License 1.0.0</a> · file <code>LICENSE</code><br /><strong>Our own graphics, animations, sounds and music:</strong> <a href="https://creativecommons.org/licenses/by-nc/4.0/deed.en" target="_blank" rel="noopener">CC BY-NC 4.0</a> · file <code>LICENSE-ASSETS</code>',
  'lic.boxCopy':
    'Copyright © 2026 Ralf Stich. The source code is openly viewable (<em>source-available</em>), but <strong>not</strong> free for commercial use.',
  'lic.ok1': 'Playing, learning, trying out, modifying and sharing for private, family, hobby, research and educational purposes.',
  'lic.ok2': 'Sharing with attribution and with the license text.',
  'lic.no1': 'Selling, renting, advertising or paid models, building it into a commercial product or a paid service.',
  'lic.dim1': 'Commercial use is only possible with written permission from Ralf Stich. The respective license text applies; this summary does not replace it.',
  'lic.dim2':
    'The non-commercial clause only applies to our own work. The third-party material below keeps its original license and stays usable for everyone as its authors permitted.',
  'lic.h.graphics': 'Graphics',
  'lic.graphics':
    'All figures in the game come from talented pixel artists who give their work to the public. Without them this game would not exist in this form. <strong>Thank you very much!</strong> We cropped every figure, partly mirrored it, assembled it into strips or tinted it.',
  'lic.creditsNote': 'The entries are in <code>public/grafik/CREDITS.md</code> and <code>public/sprites/CREDITS.md</code>; this page reads them from there.',
  'lic.warped':
    'Warped Caves Pixel Art Pack: Artwork created by Luis Zuno (@ansimuz). The source page says CC0, the license file in the pack says CC BY 3.0; we play it safe and use it under <a href="https://creativecommons.org/licenses/by/3.0/deed.en" target="_blank" rel="noopener">CC BY 3.0</a> (attribution required).',
  'lic.h.mounts': 'Notes on mounts (CC BY 3.0, attribution required)',
  'lic.mounts':
    'Horses, unicorn, pegasus, deer, elephant and wolves are licensed under <a href="https://creativecommons.org/licenses/by/3.0/deed.en" target="_blank" rel="noopener">Creative Commons Attribution 3.0</a>. We use them exclusively under CC BY 3.0 (not under the GPL variants also offered there). Our changes: cut out of the sheets, turned to face right, cropped, partly tinted; a rider sits on them in the game.',
  'lic.mountsSource':
    'Obtained via <a href="https://github.com/hckr/endless-horse-run" target="_blank" rel="noopener">hckr/endless-horse-run</a> (LPC Horses) and the collection by AntumDeluge. The horses belong to the Liberated Pixel Cup (LPC) community of <a href="https://opengameart.org" target="_blank" rel="noopener">OpenGameArt.org</a>. Thanks to everyone who shares their work there!',
  'lic.mountsTable': 'Full table with folders: <code>public/sprites/CREDITS.md</code>.',
  'lic.h.sound': 'Sound & Music',
  'lic.sound':
    'The game currently has <strong>no sound</strong>, so there is nobody to thank here yet. Once sound effects or music arrive, authors, license and source will be listed here, our own recordings under CC BY-NC 4.0.',
  'lic.h.software': 'Software',
  'lic.softwareIntro': 'These building blocks run in the game or build it. Thanks to everyone who maintains them.',
  'lic.th.part': 'Component',
  'lic.th.purpose': 'Purpose',
  'lic.th.license': 'License',
  'lic.sw.phaser': 'Game engine in the browser',
  'lic.sw.ws': 'WebSocket for online mode (Node server)',
  'lic.sw.coder': 'WebSocket in the Go server',
  'lic.sw.vite': 'Dev server and build',
  'lic.sw.ts': 'Programming language',
  'lic.sw.tests': 'Tests and lint',
  'lic.sw.go': 'Server and the game engine of the future',
  'lic.softwareNote':
    'Further tools used only for development (e.g. in <code>tools/k3c-dev</code>) are not shipped with the game; their licenses are in the respective packages.',
  'lic.h.thanks': 'Thank you',
  'lic.thanks':
    'From the heart to <strong>LuizMelo</strong>, <strong>ansimuz</strong>, <strong>bluecarrot16</strong>, <strong>Jordan Irwin (AntumDeluge)</strong>, <strong>lawnjelly</strong>, <strong>Calciumtrice</strong>, <strong>lemmling</strong>, <strong>Bonsaiheldin</strong>, <strong>vico</strong>, <strong>Rusher_go</strong> and <strong>WolfTech</strong>, to the platforms <strong>itch.io</strong> and <strong>OpenGameArt.org</strong> and to all the open-source developers above. If you enjoy their work: drop by and support them if you can.',
  'lic.thanksNote': 'Is a credit missing or wrongly assigned? Please let us know, we will fix it right away.',
};
