import type { ToolTextKey } from './texts.de';

/** Englische Texte der Werkzeug-Seiten (PL2, B-322); ein fehlender Schlüssel fällt auf Deutsch zurück. */
export const en: Partial<Record<ToolTextKey, string>> = {
  // Level viewer (leveltest.html)
  'level.pageTitle': 'K3C Level Viewer',
  'level.title': 'Level Viewer',
  'level.sub': 'Shows the level a room would get with this seed and biome, without playing. Requires the Go server to be running',
  'level.seed': 'Seed',
  'level.biome': 'Biome',
  'level.random': 'Random seed',
  'level.load': 'Load',
  'level.start': 'Start in game',
  'level.keys': 'Scroll: left stick or arrow keys · Zoom: LB/RB or + / − · Select: D-pad up/down, press A',
  'level.replaces': 'Starting opens the save named after the seed: if it exists it continues, otherwise a new game with this level begins.',
  'level.cannotStart': 'Cannot start in game: {reason}.',
  'level.chunkTitle': 'Chunk {index}: {kind} ({from}–{to} units)',
  'level.objectTitle': '{kind} at {x} units',
  'level.hubTitle': 'Hub center at {x} units',
  'level.loading': 'Loading …',
  'level.summary': 'Seed “{seed}” · {biome} · {width} units · {chunks} chunks · {objects} objects',
  'level.incomplete': 'Incomplete response',
  'level.forestOnly': 'Start only works for the forest (depth 0)',
  'level.badSeed': 'Seed must consist of lowercase letters, digits and - (at most 32 characters)',
  'level.unreachable': 'Server not reachable. Start it with `task start`.',
  'level.invalid': 'The server response is not a valid level.',
  'level.httpError': 'Error {status}',

  // Sound test (soundtest.html)
  'sound.pageTitle': 'K3C Sound Test',
  'sound.title': 'Sound Test',
  'sound.sub': 'Listen to music and effect candidates, ordered by state and event, with source and license.',
  'sound.pressKey': 'Press a key to unlock',
  'sound.stop': 'Stop',
  'sound.fade': 'Crossfade',
  'sound.volDown': 'Quieter −',
  'sound.volDownAria': 'Quieter',
  'sound.volUp': 'Louder +',
  'sound.volUpAria': 'Louder',
  'sound.keys':
    'Controller: D-pad/stick selects, A plays, X stops, Y crossfades to the selected track, LB/RB volume. ' +
    'Keyboard: arrows up/down select, Enter plays, S stops, X crossfades, arrows left/right or −/+ volume. Touch: tap an entry, buttons on top.',
  'sound.kindState': 'State',
  'sound.kindEvent': 'Event',
  'sound.failed': '{name} (does not load)',
  'sound.meta': 'Source: {source} · License: {license}',
  'sound.playing': 'Playing: {name}',
  'sound.silence': 'Silence',
  'sound.status': '{state} · Volume {volume} %',
  'sound.noFormat': 'no playable format',
  'sound.unlocked': 'Audio unlocked',
  'sound.locked': 'Audio locked: press a key, tap the screen or press A on the controller',

  // Monitoring page (monitor.html)
  'monitor.pageTitle': 'K3C Monitor',
  'monitor.connecting': 'Connecting …',
  'monitor.saveToken': 'Save token',
  'monitor.tab.overview': 'Overview',
  'monitor.tab.history': 'History',
  'monitor.tab.events': 'Events',
  'monitor.h.tick': 'Tick duration (max per s)',
  'monitor.h.rtt': 'RTT per device',
  'monitor.h.server': 'Server: heap and CPU',
  'monitor.legend': 'Red dots: outliers. Marks below: diagnostic events. Dashed: restart. ▼: selected event.',
  'monitor.keys': 'Controller: D-pad/stick selects, A confirms. Touch and mouse: tap.',
  'monitor.kind.crash': '💥 Crash',
  'monitor.kind.slow': '🐢 Slow tick',
  'monitor.kind.drop': '👋 Disconnect',
  'monitor.kind.client': '📨 Client error',
  'monitor.rooms': 'Rooms (last 5 min)',
  'monitor.noRoom': 'No active room.',
  'monitor.noPong': 'no pong',
  'monitor.roomLine': 'Tick p99 {tick} · RTT {rtt} · Errors {errors}',
  'monitor.serverLine': 'Heap {heap} MB · CPU {cpu} · Goroutines {goroutines}',
  'monitor.restart': 'Restart',
  'monitor.heapMB': 'Heap MB',
  'monitor.all': 'all',
  'monitor.roomFilter': 'Room: {room}',
  'monitor.kindFilter': 'Kind: {kind}',
  'monitor.window1h': 'Window 1 h',
  'monitor.window5m': 'Window 5 min',
  'monitor.overBudget': 'Budget exceeded',
  'monitor.ticks': '{n} ticks',
  'monitor.noEvents': 'No events in the last hour.',
  'monitor.eventRoom': ' · Room {room}',
  'monitor.tokenAsk': '🔒 Enter token (K3C_STATUS_TOKEN of the server).',
  'monitor.tokenBad': '🔒 Token missing or wrong, please enter it again.',
  'monitor.ok': '✅ As of {now} · Server since {since}',
  'monitor.off': '🚫 Diagnostics off, set K3C_STATUS_TOKEN on the server.',
  'monitor.offline': '❌ Server not reachable, next attempt in {wait} s.',

  // Dungeon master page (dm.html)
  'dm.pageTitle': 'K3C Dungeon Master',
  'dm.back': '← Room list',
  'dm.actions': 'Actions',
  'dm.monarchLabel': 'Monarch',
  'dm.rooms': 'Rooms',
  'dm.noRoom': 'No open room.',
  'dm.idle': ' · idle',
  'dm.room': 'Room {code}',
  'dm.row.tick': 'Tick',
  'dm.row.time': 'Time',
  'dm.row.wave': 'Wave',
  'dm.row.castle': 'Castle',
  'dm.row.gold': 'Gold',
  'dm.row.troops': 'Troops',
  'dm.row.devices': 'Connections',
  'dm.row.stages': 'Stages',
  'dm.timeValue': 'Day {day} · {phase} · {speed}',
  'dm.waveValue': '{wave} · Enemies {enemies}',
  'dm.monarch': 'Monarch {n}',
  'dm.unreachable': 'Server not reachable',
  'dm.devOn': 'Dev mode on · actions active',
  'dm.devOff': 'Dev mode off · diagnostics only',
  'dm.gold': '🪙 +50 gold',
  'dm.material': '📦 +20 {resource}',
  'dm.timescale': '⏩ Speed {factor}×',
  'dm.pause': '⏸ Pause',
  'dm.resume': '▶ Resume',
  'dm.wave': '🌙 Wave',
  'dm.day': '☀ Day',
  'dm.dusk': '🌆 Dusk',
  'dm.night': '🌑 Night',

  // Graphics page (grafiken.html) and credits (lizenzen.html)
  'grafik.pageTitle': 'K3C All Graphics',
  'grafik.title': 'All Graphics',
  'grafik.sub1':
    'The pixel art packs chosen for B-010 for buildings, resources and backgrounds, with author, license and source. Only the environment images are in the game folder',
  'grafik.sub2':
    'Scroll with stick or D-pad. With the “Selection” boxes (per pack and per image) you build a set of IDs below that you can mention in the chat.',
  'grafik.zoom': 'Zoom',
  'grafik.missing': 'Image missing',
  'grafik.source': 'Source',
  'grafik.noIndex': 'The image list grafik/index.json cannot be loaded.',
  'grafik.group.ebenen': 'Layers and tilesets',
  'grafik.group.umgebung': 'Environment',
  'grafik.group.props': 'Props',
  'grafik.group.props-einzeln': 'Single props',
  'grafik.group.tileset-einzeln': 'Single tilesets',
  'grafik.group.ressourcen': 'Resources',
  'grafik.group.portale': 'Portals',
  'grafik.group.muenzen': 'Coins',
  'grafik.group.icons': 'Icons',
  'grafik.group.vorschau': 'Preview',
  'credits.work': 'Work',
  'credits.author': 'Author(s)',
  'credits.license': 'License',
  'credits.source': 'Source',
  'credits.attribution': 'attribution',
};
