/**
 * Deutsche Texte der Werkzeug-Seiten (PL2, B-322): Quelle der Schlüssel, nach Seite gruppiert. Platzhalter stehen als `{name}`.
 * Deutsch ist Standard und Rückfall.
 */
export const de = {
  // Level-Betrachter (leveltest.html)
  'level.pageTitle': 'K3C Level-Betrachter',
  'level.title': 'Level-Betrachter',
  'level.sub': 'Zeigt das Level, das ein Raum mit diesem Seed und Biom bekäme, ohne zu spielen. Voraussetzung: der Go-Server läuft',
  'level.seed': 'Seed',
  'level.biome': 'Biom',
  'level.random': 'Zufälliger Seed',
  'level.load': 'Laden',
  'level.start': 'Im Spiel starten',
  'level.keys': 'Scrollen: linker Stick oder Pfeiltasten · Zoom: LB/RB oder + / − · Auswahl: Steuerkreuz hoch/runter, A drücken',
  'level.replaces': 'Der Start öffnet den Spielstand mit dem Seed als Namen: gibt es ihn schon, wird er weitergespielt, sonst entsteht ein neues Spiel mit diesem Level.',
  'level.cannotStart': 'Im Spiel starten nicht möglich: {reason}.',
  'level.chunkTitle': 'Abschnitt {index}: {kind} ({from}–{to} Units)',
  'level.objectTitle': '{kind} bei {x} Units',
  'level.hubTitle': 'Hub-Mitte bei {x} Units',
  'level.loading': 'Lade …',
  'level.summary': 'Seed „{seed}“ · {biome} · {width} Units · {chunks} Abschnitte · {objects} Objekte',
  'level.incomplete': 'Antwort unvollständig',
  'level.forestOnly': 'Start nur für den Wald (Tiefe 0)',
  'level.badSeed': 'Seed muss aus Kleinbuchstaben, Ziffern und - bestehen (höchstens 32 Zeichen)',
  'level.unreachable': 'Server nicht erreichbar. Starte ihn mit `task start`.',
  'level.invalid': 'Die Antwort des Servers ist kein gültiges Level.',
  'level.httpError': 'Fehler {status}',

  // Hörprobe (soundtest.html)
  'sound.pageTitle': 'K3C Hörprobe',
  'sound.title': 'Hörprobe',
  'sound.sub': 'Kandidaten für Musik und Effekte anhören, nach Zustand und Ereignis geordnet, mit Quelle und Lizenz.',
  'sound.pressKey': 'Taste drücken zum Entsperren',
  'sound.stop': 'Stopp',
  'sound.fade': 'Überblenden',
  'sound.volDown': 'Leiser −',
  'sound.volDownAria': 'Leiser',
  'sound.volUp': 'Lauter +',
  'sound.volUpAria': 'Lauter',
  'sound.keys':
    'Controller: Steuerkreuz/Stick wählt, A spielt, X stoppt, Y überblendet das gewählte Stück ein, LB/RB Lautstärke. ' +
    'Tastatur: Pfeile hoch/runter wählen, Enter spielt, S stoppt, X überblendet, Pfeile links/rechts oder −/+ Lautstärke. Touch: Eintrag antippen, Knöpfe oben.',
  'sound.kindState': 'Zustand',
  'sound.kindEvent': 'Ereignis',
  'sound.failed': '{name} (lädt nicht)',
  'sound.meta': 'Quelle: {source} · Lizenz: {license}',
  'sound.playing': 'Spielt: {name}',
  'sound.silence': 'Stille',
  'sound.status': '{state} · Lautstärke {volume} %',
  'sound.noFormat': 'kein abspielbares Format',
  'sound.unlocked': 'Audio entsperrt',
  'sound.locked': 'Audio gesperrt: Taste drücken, Bildschirm antippen oder A am Controller',

  // Monitoring-Seite (monitor.html)
  'monitor.pageTitle': 'K3C Monitor',
  'monitor.connecting': 'Verbinde …',
  'monitor.saveToken': 'Token speichern',
  'monitor.tab.overview': 'Übersicht',
  'monitor.tab.history': 'Verlauf',
  'monitor.tab.events': 'Ereignisse',
  'monitor.h.tick': 'Tick-Dauer (max je s)',
  'monitor.h.rtt': 'RTT je Gerät',
  'monitor.h.server': 'Server: Heap und CPU',
  'monitor.legend': 'Rote Punkte: Ausreißer. Striche unten: Diagnose-Ereignisse. Gestrichelt: Neustart. ▼: gewähltes Ereignis.',
  'monitor.keys': 'Controller: Steuerkreuz/Stick wählt, A bestätigt. Touch und Maus: antippen.',
  'monitor.kind.crash': '💥 Absturz',
  'monitor.kind.slow': '🐢 langsamer Tick',
  'monitor.kind.drop': '👋 Trennung',
  'monitor.kind.client': '📨 Client-Fehler',
  'monitor.rooms': 'Räume (letzte 5 min)',
  'monitor.noRoom': 'Kein Raum aktiv.',
  'monitor.noPong': 'kein Pong',
  'monitor.roomLine': 'Tick p99 {tick} · RTT {rtt} · Fehler {errors}',
  'monitor.serverLine': 'Heap {heap} MB · CPU {cpu} · Goroutinen {goroutines}',
  'monitor.restart': 'Neustart',
  'monitor.heapMB': 'Heap MB',
  'monitor.all': 'alle',
  'monitor.roomFilter': 'Raum: {room}',
  'monitor.kindFilter': 'Art: {kind}',
  'monitor.window1h': 'Fenster 1 h',
  'monitor.window5m': 'Fenster 5 min',
  'monitor.overBudget': 'Budget überschritten',
  'monitor.ticks': '{n} Ticks',
  'monitor.noEvents': 'Keine Ereignisse in der letzten Stunde.',
  'monitor.eventRoom': ' · Raum {room}',
  'monitor.tokenAsk': '🔒 Token eingeben (K3C_STATUS_TOKEN des Servers).',
  'monitor.tokenBad': '🔒 Token fehlt oder ist falsch, bitte neu eingeben.',
  'monitor.ok': '✅ Stand {now} · Server seit {since}',
  'monitor.off': '🚫 Diagnose aus, K3C_STATUS_TOKEN am Server setzen.',
  'monitor.offline': '❌ Server nicht erreichbar, nächster Versuch in {wait} s.',

  // Dungeon-Master-Seite (dm.html)
  'dm.pageTitle': 'K3C Dungeon Master',
  'dm.back': '← Raumliste',
  'dm.actions': 'Aktionen',
  'dm.monarchLabel': 'Monarch',
  'dm.rooms': 'Räume',
  'dm.noRoom': 'Kein Raum offen.',
  'dm.idle': ' · ruht',
  'dm.room': 'Raum {code}',
  'dm.row.tick': 'Takt',
  'dm.row.time': 'Zeit',
  'dm.row.wave': 'Welle',
  'dm.row.castle': 'Burg',
  'dm.row.gold': 'Gold',
  'dm.row.troops': 'Truppen',
  'dm.row.devices': 'Verbindungen',
  'dm.row.stages': 'Stufen',
  'dm.timeValue': 'Tag {day} · {phase} · {speed}',
  'dm.waveValue': '{wave} · Gegner {enemies}',
  'dm.monarch': 'Monarch {n}',
  'dm.unreachable': 'Server nicht erreichbar',
  'dm.devOn': 'Dev-Mode an · Aktionen aktiv',
  'dm.devOff': 'Dev-Mode aus · nur Diagnose',
  'dm.gold': '🪙 +50 Gold',
  'dm.material': '📦 +20 {resource}',
  'dm.timescale': '⏩ Zeit {factor}×',
  'dm.pause': '⏸ Pause',
  'dm.resume': '▶ Weiter',
  'dm.wave': '🌙 Welle',
  'dm.day': '☀ Tag',
  'dm.dusk': '🌆 Dämmerung',
  'dm.night': '🌑 Nacht',

  // Grafik-Seite (grafiken.html) und Credits (lizenzen.html)
  'grafik.pageTitle': 'K3C Alle Grafiken',
  'grafik.title': 'Alle Grafiken',
  'grafik.sub1':
    'Die für B-010 gewählten Pixel-Art-Packs für Gebäude, Ressourcen und Hintergründe, mit Urheber, Lizenz und Quelle. Nur die Umgebungs-Bilder sind im Spiel-Ordner',
  'grafik.sub2':
    'Scrollen mit Stick oder Steuerkreuz. Mit den Kästchen „Auswahl“ (je Pack und je Bild) stellst du unten einen Satz mit IDs zusammen, den du im Chat nennen kannst.',
  'grafik.zoom': 'Vergrößerung',
  'grafik.missing': 'Bild fehlt',
  'grafik.source': 'Quelle',
  'grafik.noIndex': 'Die Bildliste grafik/index.json lässt sich nicht laden.',
  'grafik.group.ebenen': 'Ebenen und Tilesets',
  'grafik.group.umgebung': 'Umgebung',
  'grafik.group.props': 'Props',
  'grafik.group.props-einzeln': 'Props einzeln',
  'grafik.group.tileset-einzeln': 'Tileset einzeln',
  'grafik.group.ressourcen': 'Ressourcen',
  'grafik.group.portale': 'Portale',
  'grafik.group.muenzen': 'Münzen',
  'grafik.group.icons': 'Symbole',
  'grafik.group.vorschau': 'Vorschau',
  'credits.work': 'Werk',
  'credits.author': 'Urheber:innen',
  'credits.license': 'Lizenz',
  'credits.source': 'Quelle',
  'credits.attribution': 'Namensnennung',

  // Developer page (dev.html) and its tiles; the tiles also appear on testing.html
  'dev.pageTitle': 'K3C Entwicklung',
  'dev.title': 'Entwicklung',
  'dev.sub': 'Werkzeuge für Entwicklung, Performance und Balancing. Die meisten brauchen den laufenden Go-Server.',
  'dev.section.dev': 'Entwicklung',
  'dev.section.perf': 'Performance',
  'dev.section.balance': 'Balancing',
  'dev.empty': 'Noch keine Aufrufe.',
  'tool.opening': 'Öffne „{title}“ …',
  'dev.opensWindow': '„{title}“ öffnet in einem neuen Fenster.',
  'dev.blocked': 'Neues Fenster gesperrt: {url} bitte von Hand öffnen.',
  'tile.testing.title': 'Testing',
  'tile.testing.desc': 'Test-Szenarien starten · 1 bis 4 Spieler mit Mock-Spielern (Go-Server nötig)',
  'tile.level.title': 'Level-Betrachter',
  'tile.level.desc': 'Seed und Biom wählen, das generierte Level ansehen · Warnungen der Prüfung (Go-Server nötig)',
  'tile.gamepad.title': 'Gamepad-Test',
  'tile.gamepad.desc': 'Controller, B-Taste, Vollbild, Vibration, FPS · Bericht an den PC',
  'tile.aufstellung.title': 'Unsere Aufstellung',
  'tile.aufstellung.desc': 'Jede Rolle im Spiel mit ihrer Figur · Monarchen, Truppen, Gegner',
  'tile.figuren.title': 'Alle Figuren',
  'tile.figuren.desc': 'Alle Sprites aus LuizMelo und Gothicvania, auch ungenutzte',
  'tile.grafiken.title': 'Alle Grafiken',
  'tile.grafiken.desc': 'Gewählte CC0-Packs für Gebäude, Ressourcen und Hintergründe · mit Urheber, Lizenz und Quelle',
  'tile.sound.title': 'Hörprobe',
  'tile.sound.desc': 'Kandidaten für Musik und Effekte anhören · nach Zustand und Ereignis, mit Quelle und Lizenz',
  'tile.dm.title': 'Dungeon Master',
  'tile.dm.desc': 'Laufende Räume beobachten und steuern: Zeit, Pause, Gold, Material, Welle, Tageszeit · neues Fenster (Dev-Mode des Servers)',
  'tile.monitor.title': 'Monitor',
  'tile.monitor.desc': 'Serverzustand: Ampel je Raum, Verläufe mit Perzentilen, Fehler-Zeitleiste (Go-Server mit K3C_STATUS_TOKEN)',

  // Test page (testing.html)
  'test.pageTitle': 'K3C Testing',
  'test.title': 'Testing',
  'test.sub':
    'Test-Szenarien starten oder ein Level ansehen. Du bist Spieler 1, die übrigen Spieler sind Mock-Spieler am selben Gerät: Sie erscheinen sofort und stehen still. Voraussetzung: der Go-Server läuft (<code>task serve:go</code>).',
  'test.h.players': 'Spieler',
  'test.h.level': 'Level',
  'test.starting': 'Starte „{title}“ …',
  'test.sc.one.title': '1 Spieler',
  'test.sc.n.title': '{n} Spieler',
  'test.sc.one.desc': 'Vollbild, keine Mock-Spieler',
  'test.sc.n.desc': 'Du und {mocks} Mock-Spieler (stehen still) · {layout}',
  'test.layout.2': 'zwei Streifen',
  'test.layout.3': 'zwei oben, einer breit unten',
  'test.layout.4': '2×2-Raster',

  // Reference pages (figuren.html, aufstellung.html) and the selection bar
  'fig.pageTitle': 'K3C Alle Figuren',
  'fig.title': 'Alle Figuren',
  'fig.sub':
    'Alle Figuren aus LuizMelo (unsere Seite) und Gothicvania von ansimuz (Gegenseite), auch die noch ohne Rolle. Alle CC0, Quellen in public/sprites/CREDITS.md. Jede Figur wird einzeln eingepasst. Scrollen mit Stick oder Steuerkreuz. Mit den Kästchen „Auswahl“ stellst du unten einen Satz mit den Figuren-IDs zusammen, den du im Chat nennen kannst.',
  'auf.pageTitle': 'K3C Unsere Aufstellung',
  'auf.title': 'Unsere Aufstellung',
  'auf.sub':
    'Jede Rolle im Spiel mit Bild, Einfärbung und Größe aus data/sprites.json. Monarchen, Truppen und Gegner stehen im gleichen Maßstab, so wie die Größen im Spiel zueinander passen. Unten die Figuren, die noch keine Rolle haben. Scrollen mit Stick oder Steuerkreuz. Mit den Kästchen „Auswahl“ stellst du unten einen Satz mit den Figuren-IDs zusammen, den du im Chat nennen kannst.',
  'sprite.ours': 'Unsere Seite',
  'sprite.enemy': 'Gegenseite',
  'sprite.mountsKing': 'Reittiere (mit König 1)',
  'sprite.monarchs': 'Monarchen',
  'sprite.troops': 'Truppen',
  'sprite.enemies': 'Gegner',
  'sprite.mountsLater': 'Reittiere (noch nicht im Spiel)',
  'sprite.reserve': 'Reserve (noch ohne Rolle)',
  'sprite.noRole': 'noch ohne Rolle',
  'sprite.tinted': 'eingefärbt {tint}',
  'sprite.translucent': 'durchscheinend',
  'sprite.player': 'Spieler {n}',
  'sprite.depth': '{name} · Tiefe {depth}',
  'sprite.height': '{id} · im Spiel {px} px hoch',
  'sel.pick': 'Auswahl',
  'sel.placeholder': 'Kästchen „Auswahl“ ankreuzen, der Text erscheint hier zum Kopieren',
  'sel.copy': 'Kopieren',
  'sel.clear': 'Leeren',
  'sel.text': 'Auswahl {label}: {ids}',
  'sel.figuren': 'Figuren',
  'sel.aufstellung': 'Aufstellung',
  'sel.grafiken': 'Grafiken',

  // Gamepad test (gamepad-test.html) and its audio probe
  'pad.pageTitle': 'K3C Gamepad-Test',
  'pad.sub':
    'Controller verbinden und auf jedem eine Taste drücken. Grüner Strich = Taste wurde schon einmal erkannt. Steuerung per Controller: <kbd>Y</kbd> Bericht senden · <kbd>X</kbd> Vibration · <kbd>View</kbd> FPS-Test · <kbd>Menu</kbd> Vollbild versuchen. Audiotest: erst den Abschnitt Audio ablesen, dann <kbd>A</kbd> drücken (Geste) und danach <kbd>Y</kbd> zum Senden. Bitte auch einmal <kbd>B</kbd> drücken. Zurück zur Startseite: <kbd>View</kbd>+<kbd>Menu</kbd> halten.',
  'pad.h.actions': 'Aktionen',
  'pad.btn.fullscreen': 'Vollbild',
  'pad.btn.perf': 'FPS-Test starten',
  'pad.btn.rumble': 'Vibration testen',
  'pad.btn.report': 'Bericht an Server senden',
  'pad.h.env': 'Umgebung',
  'pad.h.audio': 'Audio',
  'pad.btn.audio': 'Audio entsperren und Testton',
  'pad.h.pads': 'Controller',
  'pad.none': 'Noch kein Controller erkannt. Taste auf dem Controller drücken.',
  'pad.h.log': 'Ereignisse',
  'pad.env.secure': 'Secure Context',
  'pad.env.gamepadApi': 'Gamepad API',
  'pad.env.fullscreenApi': 'Fullscreen API',
  'pad.env.secureYes': 'ja (HTTPS/localhost)',
  'pad.env.secureNo': 'nein (HTTP)',
  'pad.env.present': 'vorhanden',
  'pad.env.missing': 'fehlt',
  'pad.env.screen': 'Bildschirm',
  'pad.env.screenValue': '{screen} · Fenster {w}x{h} · DPR {dpr}',
  'pad.env.back': 'Zurück-Navigationen',
  'pad.axis': 'Achse {i}',
  'pad.buttonN': 'Taste {i}',
  'pad.sending': 'Sende …',
  'pad.sent': '✔ Bericht gespeichert ({time})',
  'pad.sendFailed': '✘ Senden fehlgeschlagen: {error}',
  'pad.on': 'an',
  'pad.off': 'aus',
  'pad.noValues': 'keine Werte',
  'pad.audioRunning': 'Probelauf läuft …',
  'pad.log.reportSent': 'Bericht gesendet',
  'pad.log.key': 'Taste: {entry}',
  'pad.log.visibility': 'Sichtbarkeit: {state}',
  'pad.log.connected': '🎮 verbunden: #{index} {id}',
  'pad.log.disconnected': '🎮 getrennt: #{index} {id}',
  'pad.log.fullscreen': 'Vollbild: {state}',
  'pad.log.fsOk': 'Vollbild über {via}: ok',
  'pad.log.fsFailed': 'Vollbild über {via} fehlgeschlagen: {error}',
  'pad.log.rumbleNone': 'Vibration: kein Controller',
  'pad.log.rumbleOk': 'Vibration #{index}: ok',
  'pad.log.rumbleError': 'Vibration #{index}: {error}',
  'pad.log.pressed': '#{index} {name} gedrückt',
  'pad.log.perfEnd': 'FPS-Test beendet: {values}',
  'pad.log.back': '⚠ Zurück-Navigation ausgelöst (B-Taste?)',
  'pad.log.ready': 'Bereit. Taste auf einem Controller drücken.',
  'pad.log.noApi': 'Gamepad API nicht verfügbar!',
  'pad.perf.done': 'Fertig · {values} · View = zurück',
  'pad.perf.running': '{n} Sprites · {fps} FPS · Stufe {step}/{steps} · View = abbrechen',
  'audio.beforeGesture': 'Zustand vor Geste',
  'audio.afterGesture': 'Zustand nach Geste',
  'audio.noGestureYet': 'noch keine Geste',
  'audio.gestures': 'Gesten',
  'audio.autoplay': 'Abspielen ohne Geste',
  'audio.played': 'gespielt',
  'audio.blocked': 'blockiert',
  'audio.error': 'fehler: {name}',
  'audio.format': 'Format {format}',
  'audio.yes': 'ja',
  'audio.no': 'nein',
  'audio.latency': 'Latenz',
  'audio.latencyValue': 'Basis {base} · Ausgabe {out}',
  'audio.unknown': 'unbekannt',
  'audio.none': 'kein Audio (kein AudioContext)',
  'audio.via.controller': 'controller',
  'audio.via.taste': 'taste',
  'audio.via.klick': 'klick',

  // Licenses page (lizenzen.html); texts with HTML are set via data-t-html
  'lic.pageTitle': 'K3C Lizenzen & Danksagung',
  'lic.title': 'Lizenzen & Danksagung',
  'lic.sub':
    'Family Three Crowns (K3C) ist ein Familienprojekt und steht auf den Schultern vieler großzügiger Menschen. Hier steht, unter welcher Lizenz unser Spiel läuft und wem wir für Grafiken, Bibliotheken und Werkzeuge danken. Scrollen mit Stick oder Steuerkreuz.',
  'lic.h.ours': 'Unsere Lizenz',
  'lic.boxCode':
    '<strong>Quelltext:</strong> <a href="https://polyformproject.org/licenses/noncommercial/1.0.0" target="_blank" rel="noopener">PolyForm Noncommercial License 1.0.0</a> · Datei <code>LICENSE</code><br /><strong>Eigene Grafiken, Animationen, Sounds und Musik:</strong> <a href="https://creativecommons.org/licenses/by-nc/4.0/deed.de" target="_blank" rel="noopener">CC BY-NC 4.0</a> · Datei <code>LICENSE-ASSETS</code>',
  'lic.boxCopy':
    'Copyright © 2026 Ralf Stich. Der Quelltext ist offen einsehbar (<em>source-available</em>), aber <strong>nicht</strong> frei für kommerzielle Nutzung.',
  'lic.ok1': 'Spielen, Lernen, Ausprobieren, Verändern und Weitergeben zu privaten, familiären, Hobby-, Forschungs- und Bildungszwecken.',
  'lic.ok2': 'Weitergabe mit Namensnennung und mit dem Lizenztext.',
  'lic.no1': 'Verkaufen, Vermieten, Werbung oder Bezahlmodelle, Einbau in ein kommerzielles Produkt oder eine bezahlte Dienstleistung.',
  'lic.dim1': 'Kommerzielle Nutzung ist nur mit schriftlicher Erlaubnis von Ralf Stich möglich. Es gilt der jeweilige Lizenztext, diese Zusammenfassung ersetzt ihn nicht.',
  'lic.dim2':
    'Die Nicht-kommerziell-Klausel gilt nur für unsere eigene Arbeit. Das Fremdmaterial unten behält seine ursprüngliche Lizenz und bleibt für alle so nutzbar, wie die Urheber:innen es erlaubt haben.',
  'lic.h.graphics': 'Grafiken',
  'lic.graphics':
    'Alle Figuren im Spiel stammen von talentierten Pixel-Künstler:innen, die ihre Arbeit der Allgemeinheit schenken. Ohne sie gäbe es dieses Spiel in dieser Form nicht. <strong>Vielen herzlichen Dank!</strong> Jede Figur wurde von uns zugeschnitten, teils gespiegelt, zu Streifen zusammengesetzt oder eingefärbt.',
  'lic.creditsNote': 'Die Einträge stehen in <code>public/grafik/CREDITS.md</code> und <code>public/sprites/CREDITS.md</code>; diese Seite liest sie von dort.',
  'lic.warped':
    'Warped Caves Pixel Art Pack: Artwork created by Luis Zuno (@ansimuz). Die Quellseite nennt CC0, die Lizenzdatei im Pack CC BY 3.0; wir nutzen es vorsichtig unter <a href="https://creativecommons.org/licenses/by/3.0/deed.de" target="_blank" rel="noopener">CC BY 3.0</a> (Namensnennung Pflicht).',
  'lic.h.mounts': 'Hinweise zu Reittieren (CC BY 3.0, Namensnennung Pflicht)',
  'lic.mounts':
    'Pferde, Einhorn, Pegasus, Hirsch, Elefant und Wölfe sind unter <a href="https://creativecommons.org/licenses/by/3.0/deed.de" target="_blank" rel="noopener">Creative Commons Namensnennung 3.0</a> lizenziert. Wir nutzen sie ausschließlich unter CC BY 3.0 (nicht unter den dort ebenfalls angebotenen GPL-Varianten). Änderungen durch uns: aus den Sheets herausgeschnitten, auf Blickrichtung rechts gebracht, zugeschnitten, teils eingefärbt; darauf sitzt im Spiel ein Reiter.',
  'lic.mountsSource':
    'Bezogen über <a href="https://github.com/hckr/endless-horse-run" target="_blank" rel="noopener">hckr/endless-horse-run</a> (LPC Horses) und die Sammlung von AntumDeluge. Die Pferde gehören zur Liberated Pixel Cup (LPC) Community von <a href="https://opengameart.org" target="_blank" rel="noopener">OpenGameArt.org</a>. Danke an alle, die dort ihre Werke teilen!',
  'lic.mountsTable': 'Vollständige Tabelle mit Ordnern: <code>public/sprites/CREDITS.md</code>.',
  'lic.h.sound': 'Sound & Musik',
  'lic.sound':
    'Das Spiel hat derzeit <strong>keinen Ton</strong>, daher gibt es hier noch nichts zu danken. Sobald Soundeffekte oder Musik einziehen, stehen Urheber:innen, Lizenz und Quelle an dieser Stelle, eigene Aufnahmen unter CC BY-NC 4.0.',
  'lic.h.software': 'Software',
  'lic.softwareIntro': 'Diese Bausteine laufen im Spiel oder bauen es. Danke an alle, die sie pflegen.',
  'lic.th.part': 'Baustein',
  'lic.th.purpose': 'Wofür',
  'lic.th.license': 'Lizenz',
  'lic.sw.phaser': 'Spiel-Engine im Browser',
  'lic.sw.ws': 'WebSocket für den Online-Modus (Node-Server)',
  'lic.sw.coder': 'WebSocket im Go-Server',
  'lic.sw.vite': 'Dev-Server und Build',
  'lic.sw.ts': 'Programmiersprache',
  'lic.sw.tests': 'Tests und Lint',
  'lic.sw.go': 'Server und Spiel-Engine der Zukunft',
  'lic.softwareNote':
    'Weitere Werkzeuge nur für die Entwicklung (z. B. in <code>tools/k3c-dev</code>) liefern wir nicht mit dem Spiel aus; ihre Lizenzen liegen in den jeweiligen Paketen.',
  'lic.h.thanks': 'Danke',
  'lic.thanks':
    'Von Herzen an <strong>LuizMelo</strong>, <strong>ansimuz</strong>, <strong>bluecarrot16</strong>, <strong>Jordan Irwin (AntumDeluge)</strong>, <strong>lawnjelly</strong>, <strong>Calciumtrice</strong>, <strong>lemmling</strong>, <strong>Bonsaiheldin</strong>, <strong>vico</strong>, <strong>Rusher_go</strong> und <strong>WolfTech</strong>, an die Plattformen <strong>itch.io</strong> und <strong>OpenGameArt.org</strong> und an alle Open-Source-Entwickler:innen oben. Wer Freude an ihren Werken hat: Schaut bei ihnen vorbei und unterstützt sie, wenn ihr könnt.',
  'lic.thanksNote': 'Fehlt eine Nennung oder ist etwas falsch zugeordnet? Bitte melden, wir korrigieren es umgehend.',
} as const satisfies Record<string, string>;

export type ToolTextKey = keyof typeof de;
